apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-ingress
  namespace: {{.Values.namespace}}
  labels:
    name: laravel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingresslaravel.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingresslaravel.path }}
        backend:
          service:
            name: laravel-service
            port: 
              number: 8000
