apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
  namespace: {{.Values.namespace}}
spec:
  capacity:
    storage: {{ .Values.persistentVolumes.laravel.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: laravel-sc
  hostPath:
    path: {{ .Values.persistentVolumes.laravel.hostpath }}
