apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc
  namespace: {{.Values.namespace}}
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.laravel.requestStorage }}
  storageClassName: laravel-sc
  accessModes:
    - ReadWriteOnce
