apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  LARAVEL_DATABASE_NAME: {{ .Values.bbddconfig.db | quote}}
  LARAVEL_DATABASE_USER: {{ .Values.bbddconfig.user | quote}}
  LARAVEL_DATABASE_PASSWORD: {{ .Values.bbddconfig.password | quote}}
