apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{.Values.namespace}}
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.mysql.requestStorage }}
  storageClassName: mysql-sc
  accessModes:
    - ReadWriteOnce
