apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stfs-{{ .Release.Name }}
  namespace: {{.Values.namespace}}
  labels:
    exercise: weekly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbdd
  serviceName: bbdd-svc
  template:
    metadata:
      labels:
        app: bbdd
    spec:    
      containers:
      - name: bbdd
        image: mysql:{{ .Values.mysql.tag }}
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: db
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: root-password
          - name: MYSQL_INITDB_SKIP_TZINFO
            value: skip
        resources: 
          requests:
            memory: {{ .Values.mysql.resources.requests.memory }}
            cpu: {{ .Values.mysql.resources.requests.cpu }}
          limits:
            memory: {{ .Values.mysql.resources.limits.memory }}
            cpu: {{ .Values.mysql.resources.limits.cpu }}
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
