apiVersion: v1
kind: Secret
metadata:
  name: bdsecrets
  namespace: {{.Values.namespace}}
type: Opaque
stringData:
  user: {{ .Values.bbddconfig.user | quote}}
  password: {{ .Values.bbddconfig.password | quote}}
  root-password: {{ .Values.bbddconfig.rootpassword | quote}}
  db: {{ .Values.bbddconfig.db | quote}}