apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1-pv
  namespace: {{.Values.namespace}}
spec:
  capacity:
    storage: {{ .Values.persistentVolumes.mysql.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-sc
  hostPath:
    path: {{ .Values.persistentVolumes.mysql.hostpath }}
