{{- if .Values.withPhpmyadmin }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy-{{ .Release.Name }}
  namespace: {{.Values.namespace}}
  labels:
    exercise: weekly
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:{{ .Values.phpmyadmin.tag }}
        ports:
        - containerPort: 80
        env:
          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: phpmyadmin-configmap
                key: PMA_HOST
          - name: PMA_PORT
            valueFrom:
              configMapKeyRef:
                name: phpmyadmin-configmap
                key: PMA_PORT
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: password
          - name: PMA_ARBITRARY
            value: "1"
        resources: 
          requests:
            memory: {{ .Values.phpmyadmin.resources.requests.memory }}
            cpu: {{ .Values.phpmyadmin.resources.requests.cpu }}
          limits:
            memory: {{ .Values.phpmyadmin.resources.limits.memory }}
            cpu: {{ .Values.phpmyadmin.resources.limits.cpu }}
{{- end -}}