apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1-pv
  namespace: laravel
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-sc
  hostPath:
    path: /mnt/data/mysql
