apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bbdd
  namespace: laravel
  labels:
    exercise: weekly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbdd
  serviceName: bbdd-svc
  template:
    metadata:
      labels:
        app: bbdd
    spec:    
      containers:
      - name: bbdd
        image: mysql:8.4
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: db
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bdsecrets
                key: password
          - name: MYSQL_INITDB_SKIP_TZINFO
            value: skip
        resources: 
          requests:
            cpu: "800m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "700Mi"
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
