apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel1-pv
  namespace: laravel
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: laravel-sc
  hostPath:
    path: /mnt/data/laravel
