apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc
  namespace: laravel
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: laravel-sc
  accessModes:
    - ReadWriteOnce
