apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel
type: Opaque
stringData:
  LARAVEL_DATABASE_NAME: "laravel"
  LARAVEL_DATABASE_USER: "rafa"
  LARAVEL_DATABASE_PASSWORD: "1234"
